# resolve-type-names: false

class ::SyncRun < ::ApplicationRecord
  class ::SyncRun::Failure < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::SyncRun::Failure, ::SyncRun::Failure::ActiveRecord_Relation, ::Integer]

    module ::SyncRun::Failure::GeneratedAttributeMethods
      def id: () -> ::Integer

      def id=: (::Integer) -> ::Integer

      def id?: () -> bool

      def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_change: () -> [ ::Integer?, ::Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> ::Integer?

      def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_previous_change: () -> ::Array[::Integer?]?

      def id_previously_was: () -> ::Integer?

      def id_before_last_save: () -> ::Integer?

      def id_change_to_be_saved: () -> ::Array[::Integer?]?

      def id_in_database: () -> ::Integer?

      def saved_change_to_id: () -> ::Array[::Integer?]?

      def saved_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::Integer

      def id_for_database: () -> ::Integer

      def sync_run_id: () -> ::Integer

      def sync_run_id=: (::Integer) -> ::Integer

      def sync_run_id?: () -> bool

      def sync_run_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def sync_run_id_change: () -> [ ::Integer?, ::Integer? ]

      def sync_run_id_will_change!: () -> void

      def sync_run_id_was: () -> ::Integer?

      def sync_run_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def sync_run_id_previous_change: () -> ::Array[::Integer?]?

      def sync_run_id_previously_was: () -> ::Integer?

      def sync_run_id_before_last_save: () -> ::Integer?

      def sync_run_id_change_to_be_saved: () -> ::Array[::Integer?]?

      def sync_run_id_in_database: () -> ::Integer?

      def saved_change_to_sync_run_id: () -> ::Array[::Integer?]?

      def saved_change_to_sync_run_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_sync_run_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_sync_run_id!: () -> void

      def clear_sync_run_id_change: () -> void

      def sync_run_id_before_type_cast: () -> ::Integer

      def sync_run_id_for_database: () -> ::Integer

      def entity_type: () -> ::String

      def entity_type=: (::String) -> ::String

      def entity_type?: () -> bool

      def entity_type_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def entity_type_change: () -> [ ::String?, ::String? ]

      def entity_type_will_change!: () -> void

      def entity_type_was: () -> ::String?

      def entity_type_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def entity_type_previous_change: () -> ::Array[::String?]?

      def entity_type_previously_was: () -> ::String?

      def entity_type_before_last_save: () -> ::String?

      def entity_type_change_to_be_saved: () -> ::Array[::String?]?

      def entity_type_in_database: () -> ::String?

      def saved_change_to_entity_type: () -> ::Array[::String?]?

      def saved_change_to_entity_type?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_entity_type?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_entity_type!: () -> void

      def clear_entity_type_change: () -> void

      def entity_type_before_type_cast: () -> ::String

      def entity_type_for_database: () -> ::String

      def external_id: () -> ::String

      def external_id=: (::String) -> ::String

      def external_id?: () -> bool

      def external_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def external_id_change: () -> [ ::String?, ::String? ]

      def external_id_will_change!: () -> void

      def external_id_was: () -> ::String?

      def external_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def external_id_previous_change: () -> ::Array[::String?]?

      def external_id_previously_was: () -> ::String?

      def external_id_before_last_save: () -> ::String?

      def external_id_change_to_be_saved: () -> ::Array[::String?]?

      def external_id_in_database: () -> ::String?

      def saved_change_to_external_id: () -> ::Array[::String?]?

      def saved_change_to_external_id?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_external_id?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_external_id!: () -> void

      def clear_external_id_change: () -> void

      def external_id_before_type_cast: () -> ::String

      def external_id_for_database: () -> ::String

      def error_class: () -> ::String

      def error_class=: (::String) -> ::String

      def error_class?: () -> bool

      def error_class_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def error_class_change: () -> [ ::String?, ::String? ]

      def error_class_will_change!: () -> void

      def error_class_was: () -> ::String?

      def error_class_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def error_class_previous_change: () -> ::Array[::String?]?

      def error_class_previously_was: () -> ::String?

      def error_class_before_last_save: () -> ::String?

      def error_class_change_to_be_saved: () -> ::Array[::String?]?

      def error_class_in_database: () -> ::String?

      def saved_change_to_error_class: () -> ::Array[::String?]?

      def saved_change_to_error_class?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_error_class?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_error_class!: () -> void

      def clear_error_class_change: () -> void

      def error_class_before_type_cast: () -> ::String

      def error_class_for_database: () -> ::String

      def message: () -> ::String?

      def message=: (::String?) -> ::String?

      def message?: () -> bool

      def message_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def message_change: () -> [ ::String?, ::String? ]

      def message_will_change!: () -> void

      def message_was: () -> ::String?

      def message_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def message_previous_change: () -> ::Array[::String?]?

      def message_previously_was: () -> ::String?

      def message_before_last_save: () -> ::String?

      def message_change_to_be_saved: () -> ::Array[::String?]?

      def message_in_database: () -> ::String?

      def saved_change_to_message: () -> ::Array[::String?]?

      def saved_change_to_message?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_message?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_message!: () -> void

      def clear_message_change: () -> void

      def message_before_type_cast: () -> ::String?

      def message_for_database: () -> ::String?

      def payload: () -> untyped

      def payload=: (untyped) -> untyped

      def payload?: () -> bool

      def payload_changed?: (?from: untyped, ?to: untyped) -> bool

      def payload_change: () -> [ untyped, untyped ]

      def payload_will_change!: () -> void

      def payload_was: () -> untyped

      def payload_previously_changed?: (?from: untyped, ?to: untyped) -> bool

      def payload_previous_change: () -> ::Array[untyped]?

      def payload_previously_was: () -> untyped

      def payload_before_last_save: () -> untyped

      def payload_change_to_be_saved: () -> ::Array[untyped]?

      def payload_in_database: () -> untyped

      def saved_change_to_payload: () -> ::Array[untyped]?

      def saved_change_to_payload?: (?from: untyped, ?to: untyped) -> bool

      def will_save_change_to_payload?: (?from: untyped, ?to: untyped) -> bool

      def restore_payload!: () -> void

      def clear_payload_change: () -> void

      def payload_before_type_cast: () -> untyped?

      def payload_for_database: () -> untyped?

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time
    end
    include ::SyncRun::Failure::GeneratedAttributeMethods
    module ::SyncRun::Failure::GeneratedAliasAttributeMethods
      include ::SyncRun::Failure::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::SyncRun::Failure::GeneratedAliasAttributeMethods

    def sync_run: () -> ::SyncRun
    def sync_run=: (::SyncRun?) -> ::SyncRun?
    def reload_sync_run: () -> ::SyncRun?
    def build_sync_run: (?untyped) -> ::SyncRun
    def create_sync_run: (?untyped) -> ::SyncRun
    def create_sync_run!: (?untyped) -> ::SyncRun

    module ::SyncRun::Failure::GeneratedAssociationMethods
    end
    include ::SyncRun::Failure::GeneratedAssociationMethods

    module ::SyncRun::Failure::GeneratedRelationMethods
    end

    class ::SyncRun::Failure::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::SyncRun::Failure]
      include ::SyncRun::Failure::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::SyncRun::Failure, ::Integer]
    end

    class ::SyncRun::Failure::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::SyncRun::Failure]
      include ::SyncRun::Failure::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::SyncRun::Failure, ::Integer]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SyncRun::Failure
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SyncRun::Failure]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SyncRun::Failure
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SyncRun::Failure]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SyncRun::Failure
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SyncRun::Failure]
      def reload: () -> ::Array[::SyncRun::Failure]

      def replace: (::Array[::SyncRun::Failure]) -> void
      def delete: (*::SyncRun::Failure | ::Integer) -> ::Array[::SyncRun::Failure]
      def destroy: (*::SyncRun::Failure | ::Integer) -> ::Array[::SyncRun::Failure]
      def <<: (*::SyncRun::Failure | ::Array[::SyncRun::Failure]) -> self
      def prepend: (*::SyncRun::Failure | ::Array[::SyncRun::Failure]) -> self
    end
  end
end

class ::SyncRun < ::ApplicationRecord
end
class ::ApplicationRecord < ::ActiveRecord::Base
end
