# frozen_string_literal: true

# Builds Active Admin's Tailwind v4 stylesheet using the standalone Tailwind CLI
# shipped by the tailwindcss-ruby gem — no Node.js / npm required.
#
# The generated `tailwind-active_admin.config.js` resolves Active Admin's plugin
# and view templates straight from the installed gem, so it keeps working across
# `bundle update activeadmin`. The file is regenerated on every build and is
# therefore git-ignored.
require 'tailwindcss/ruby'

module ActiveAdminTailwind
  module_function

  def gem_path
    spec = Gem.loaded_specs['activeadmin']
    raise 'activeadmin gem is not loaded — run inside the Rails environment' unless spec

    spec.full_gem_path
  end

  def write_config! # rubocop:disable Metrics/MethodLength
    aa = gem_path
    Rails.root.join('tailwind-active_admin.config.js').write(<<~JS)
      // Generated by `rails active_admin:build` — do not edit.
      // Paths are machine-specific and resolved from the installed activeadmin gem.
      import activeAdminPlugin from '#{aa}/plugin.js';

      export default {
        content: [
          '#{aa}/vendor/javascript/flowbite.js',
          '#{aa}/plugin.js',
          '#{aa}/app/views/**/*.{arb,erb,html,rb}',
          './app/admin/**/*.{arb,erb,html,rb}',
          './app/views/active_admin/**/*.{arb,erb,html,rb}',
          './app/views/admin/**/*.{arb,erb,html,rb}',
          './app/views/layouts/active_admin*.{erb,html}',
          './app/javascript/**/*.js'
        ],
        darkMode: 'selector',
        plugins: [activeAdminPlugin]
      }
    JS
  end

  def compile(*extra)
    command = [
      Tailwindcss::Ruby.executable.to_s,
      '-i', Rails.root.join('app/assets/tailwind/active_admin.css').to_s,
      '-o', Rails.root.join('app/assets/builds/active_admin.css').to_s,
      *extra
    ]
    system(*command, exception: true)
  end
end

namespace :active_admin do
  desc "Build Active Admin's Tailwind stylesheet (no Node required)"
  task build: :environment do
    ActiveAdminTailwind.write_config!
    ActiveAdminTailwind.compile('--minify')
  end

  desc "Watch and rebuild Active Admin's Tailwind stylesheet"
  task watch: :environment do
    ActiveAdminTailwind.write_config!
    ActiveAdminTailwind.compile('--watch')
  end
end

# Compile the admin stylesheet automatically during asset precompilation (deploys).
Rake::Task['assets:precompile'].enhance([ 'active_admin:build' ]) if Rake::Task.task_defined?('assets:precompile')
