class Pharmapoint::AtcClass < Data
  attr_reader external_id: String
  attr_reader atc_code: String?
  attr_reader name: String?
  attr_reader ancestors: Array[Pharmapoint::AtcEntry]

  def self.new: (external_id: String, atc_code: String?, name: String?, ancestors: Array[Pharmapoint::AtcEntry]) -> instance

  def as_json: () -> Pharmapoint::Logging::Masker::tree
end
