class Pharmapoint::Producer < Data
  attr_reader external_id: String
  attr_reader name: String?
  attr_reader country: String?
  attr_reader country_code: String?

  def self.new: (external_id: String, name: String?, country: String?, country_code: String?) -> instance

  def as_json: () -> Pharmapoint::Logging::Masker::tree
end
