# frozen_string_literal: true

module Overcommit::Hook::PreCommit
  # Runs Steep over the project. The signatures of models are generated by rbs_rails into .rbs_rails/, which is not in
  # git, so a fresh clone has none until `mise run rbs` has been run; the hook says so instead of failing on it.
  class Steep < Base
    GENERATED_SIGNATURES = '.rbs_rails'

    def run
      unless Dir.exist?(File.join(Overcommit::Utils.repo_root, GENERATED_SIGNATURES))
        return [ :warn, "#{GENERATED_SIGNATURES} is missing, Steep was not run. Generate it with `mise run rbs`." ]
      end

      result = execute(command)
      return :pass if result.success?

      [ :fail, utf8("#{result.stdout}#{result.stderr}").strip ]
    end

    private

    # Steep prints Unicode, while a hook may run under a locale that reads output as US-ASCII.
    def utf8(text) = text.dup.force_encoding(Encoding::UTF_8).scrub
  end
end
