# resolve-type-names: false

module ::H24Auth
  class ::H24Auth::Employee < ::H24Auth::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::H24Auth::Employee, ::H24Auth::Employee::ActiveRecord_Relation, ::Integer]

    module ::H24Auth::Employee::GeneratedAttributeMethods
      def Id: () -> ::Integer

      def Id=: (::Integer) -> ::Integer

      def Id?: () -> bool

      def Id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def Id_change: () -> [ ::Integer?, ::Integer? ]

      def Id_will_change!: () -> void

      def Id_was: () -> ::Integer?

      def Id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def Id_previous_change: () -> ::Array[::Integer?]?

      def Id_previously_was: () -> ::Integer?

      def Id_before_last_save: () -> ::Integer?

      def Id_change_to_be_saved: () -> ::Array[::Integer?]?

      def Id_in_database: () -> ::Integer?

      def saved_change_to_Id: () -> ::Array[::Integer?]?

      def saved_change_to_Id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_Id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_Id!: () -> void

      def clear_Id_change: () -> void

      def Id_before_type_cast: () -> ::Integer

      def Id_for_database: () -> ::Integer

      def PartyId: () -> ::Integer

      def PartyId=: (::Integer) -> ::Integer

      def PartyId?: () -> bool

      def PartyId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def PartyId_change: () -> [ ::Integer?, ::Integer? ]

      def PartyId_will_change!: () -> void

      def PartyId_was: () -> ::Integer?

      def PartyId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def PartyId_previous_change: () -> ::Array[::Integer?]?

      def PartyId_previously_was: () -> ::Integer?

      def PartyId_before_last_save: () -> ::Integer?

      def PartyId_change_to_be_saved: () -> ::Array[::Integer?]?

      def PartyId_in_database: () -> ::Integer?

      def saved_change_to_PartyId: () -> ::Array[::Integer?]?

      def saved_change_to_PartyId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_PartyId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_PartyId!: () -> void

      def clear_PartyId_change: () -> void

      def PartyId_before_type_cast: () -> ::Integer

      def PartyId_for_database: () -> ::Integer

      def DivisionId: () -> ::Integer?

      def DivisionId=: (::Integer?) -> ::Integer?

      def DivisionId?: () -> bool

      def DivisionId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def DivisionId_change: () -> [ ::Integer?, ::Integer? ]

      def DivisionId_will_change!: () -> void

      def DivisionId_was: () -> ::Integer?

      def DivisionId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def DivisionId_previous_change: () -> ::Array[::Integer?]?

      def DivisionId_previously_was: () -> ::Integer?

      def DivisionId_before_last_save: () -> ::Integer?

      def DivisionId_change_to_be_saved: () -> ::Array[::Integer?]?

      def DivisionId_in_database: () -> ::Integer?

      def saved_change_to_DivisionId: () -> ::Array[::Integer?]?

      def saved_change_to_DivisionId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_DivisionId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_DivisionId!: () -> void

      def clear_DivisionId_change: () -> void

      def DivisionId_before_type_cast: () -> ::Integer?

      def DivisionId_for_database: () -> ::Integer?

      def PositionRefId: () -> ::Integer?

      def PositionRefId=: (::Integer?) -> ::Integer?

      def PositionRefId?: () -> bool

      def PositionRefId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def PositionRefId_change: () -> [ ::Integer?, ::Integer? ]

      def PositionRefId_will_change!: () -> void

      def PositionRefId_was: () -> ::Integer?

      def PositionRefId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def PositionRefId_previous_change: () -> ::Array[::Integer?]?

      def PositionRefId_previously_was: () -> ::Integer?

      def PositionRefId_before_last_save: () -> ::Integer?

      def PositionRefId_change_to_be_saved: () -> ::Array[::Integer?]?

      def PositionRefId_in_database: () -> ::Integer?

      def saved_change_to_PositionRefId: () -> ::Array[::Integer?]?

      def saved_change_to_PositionRefId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_PositionRefId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_PositionRefId!: () -> void

      def clear_PositionRefId_change: () -> void

      def PositionRefId_before_type_cast: () -> ::Integer?

      def PositionRefId_for_database: () -> ::Integer?

      def StartDate: () -> ::Date?

      def StartDate=: (::Date?) -> ::Date?

      def StartDate?: () -> bool

      def StartDate_changed?: (?from: ::Date?, ?to: ::Date?) -> bool

      def StartDate_change: () -> [ ::Date?, ::Date? ]

      def StartDate_will_change!: () -> void

      def StartDate_was: () -> ::Date?

      def StartDate_previously_changed?: (?from: ::Date?, ?to: ::Date?) -> bool

      def StartDate_previous_change: () -> ::Array[::Date?]?

      def StartDate_previously_was: () -> ::Date?

      def StartDate_before_last_save: () -> ::Date?

      def StartDate_change_to_be_saved: () -> ::Array[::Date?]?

      def StartDate_in_database: () -> ::Date?

      def saved_change_to_StartDate: () -> ::Array[::Date?]?

      def saved_change_to_StartDate?: (?from: ::Date?, ?to: ::Date?) -> bool

      def will_save_change_to_StartDate?: (?from: ::Date?, ?to: ::Date?) -> bool

      def restore_StartDate!: () -> void

      def clear_StartDate_change: () -> void

      def StartDate_before_type_cast: () -> ::Date?

      def StartDate_for_database: () -> ::Date?

      def EndDate: () -> ::Date?

      def EndDate=: (::Date?) -> ::Date?

      def EndDate?: () -> bool

      def EndDate_changed?: (?from: ::Date?, ?to: ::Date?) -> bool

      def EndDate_change: () -> [ ::Date?, ::Date? ]

      def EndDate_will_change!: () -> void

      def EndDate_was: () -> ::Date?

      def EndDate_previously_changed?: (?from: ::Date?, ?to: ::Date?) -> bool

      def EndDate_previous_change: () -> ::Array[::Date?]?

      def EndDate_previously_was: () -> ::Date?

      def EndDate_before_last_save: () -> ::Date?

      def EndDate_change_to_be_saved: () -> ::Array[::Date?]?

      def EndDate_in_database: () -> ::Date?

      def saved_change_to_EndDate: () -> ::Array[::Date?]?

      def saved_change_to_EndDate?: (?from: ::Date?, ?to: ::Date?) -> bool

      def will_save_change_to_EndDate?: (?from: ::Date?, ?to: ::Date?) -> bool

      def restore_EndDate!: () -> void

      def clear_EndDate_change: () -> void

      def EndDate_before_type_cast: () -> ::Date?

      def EndDate_for_database: () -> ::Date?

      def ApiId: () -> ::String?

      def ApiId=: (::String?) -> ::String?

      def ApiId?: () -> bool

      def ApiId_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def ApiId_change: () -> [ ::String?, ::String? ]

      def ApiId_will_change!: () -> void

      def ApiId_was: () -> ::String?

      def ApiId_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def ApiId_previous_change: () -> ::Array[::String?]?

      def ApiId_previously_was: () -> ::String?

      def ApiId_before_last_save: () -> ::String?

      def ApiId_change_to_be_saved: () -> ::Array[::String?]?

      def ApiId_in_database: () -> ::String?

      def saved_change_to_ApiId: () -> ::Array[::String?]?

      def saved_change_to_ApiId?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_ApiId?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_ApiId!: () -> void

      def clear_ApiId_change: () -> void

      def ApiId_before_type_cast: () -> ::String?

      def ApiId_for_database: () -> ::String?

      def SpecialityOfficioId: () -> ::Integer?

      def SpecialityOfficioId=: (::Integer?) -> ::Integer?

      def SpecialityOfficioId?: () -> bool

      def SpecialityOfficioId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def SpecialityOfficioId_change: () -> [ ::Integer?, ::Integer? ]

      def SpecialityOfficioId_will_change!: () -> void

      def SpecialityOfficioId_was: () -> ::Integer?

      def SpecialityOfficioId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def SpecialityOfficioId_previous_change: () -> ::Array[::Integer?]?

      def SpecialityOfficioId_previously_was: () -> ::Integer?

      def SpecialityOfficioId_before_last_save: () -> ::Integer?

      def SpecialityOfficioId_change_to_be_saved: () -> ::Array[::Integer?]?

      def SpecialityOfficioId_in_database: () -> ::Integer?

      def saved_change_to_SpecialityOfficioId: () -> ::Array[::Integer?]?

      def saved_change_to_SpecialityOfficioId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_SpecialityOfficioId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_SpecialityOfficioId!: () -> void

      def clear_SpecialityOfficioId_change: () -> void

      def SpecialityOfficioId_before_type_cast: () -> ::Integer?

      def SpecialityOfficioId_for_database: () -> ::Integer?

      def IsOnPortal: () -> bool

      def IsOnPortal=: (bool) -> bool

      def IsOnPortal?: () -> bool

      def IsOnPortal_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsOnPortal_change: () -> [ bool?, bool? ]

      def IsOnPortal_will_change!: () -> void

      def IsOnPortal_was: () -> bool?

      def IsOnPortal_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsOnPortal_previous_change: () -> ::Array[bool?]?

      def IsOnPortal_previously_was: () -> bool?

      def IsOnPortal_before_last_save: () -> bool?

      def IsOnPortal_change_to_be_saved: () -> ::Array[bool?]?

      def IsOnPortal_in_database: () -> bool?

      def saved_change_to_IsOnPortal: () -> ::Array[bool?]?

      def saved_change_to_IsOnPortal?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_IsOnPortal?: (?from: bool?, ?to: bool?) -> bool

      def restore_IsOnPortal!: () -> void

      def clear_IsOnPortal_change: () -> void

      def IsOnPortal_before_type_cast: () -> bool

      def IsOnPortal_for_database: () -> bool

      def Rating: () -> ::Float?

      def Rating=: (::Float?) -> ::Float?

      def Rating?: () -> bool

      def Rating_changed?: (?from: ::Float?, ?to: ::Float?) -> bool

      def Rating_change: () -> [ ::Float?, ::Float? ]

      def Rating_will_change!: () -> void

      def Rating_was: () -> ::Float?

      def Rating_previously_changed?: (?from: ::Float?, ?to: ::Float?) -> bool

      def Rating_previous_change: () -> ::Array[::Float?]?

      def Rating_previously_was: () -> ::Float?

      def Rating_before_last_save: () -> ::Float?

      def Rating_change_to_be_saved: () -> ::Array[::Float?]?

      def Rating_in_database: () -> ::Float?

      def saved_change_to_Rating: () -> ::Array[::Float?]?

      def saved_change_to_Rating?: (?from: ::Float?, ?to: ::Float?) -> bool

      def will_save_change_to_Rating?: (?from: ::Float?, ?to: ::Float?) -> bool

      def restore_Rating!: () -> void

      def clear_Rating_change: () -> void

      def Rating_before_type_cast: () -> ::Float?

      def Rating_for_database: () -> ::Float?

      def ReviewCount: () -> ::Integer

      def ReviewCount=: (::Integer) -> ::Integer

      def ReviewCount?: () -> bool

      def ReviewCount_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def ReviewCount_change: () -> [ ::Integer?, ::Integer? ]

      def ReviewCount_will_change!: () -> void

      def ReviewCount_was: () -> ::Integer?

      def ReviewCount_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def ReviewCount_previous_change: () -> ::Array[::Integer?]?

      def ReviewCount_previously_was: () -> ::Integer?

      def ReviewCount_before_last_save: () -> ::Integer?

      def ReviewCount_change_to_be_saved: () -> ::Array[::Integer?]?

      def ReviewCount_in_database: () -> ::Integer?

      def saved_change_to_ReviewCount: () -> ::Array[::Integer?]?

      def saved_change_to_ReviewCount?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_ReviewCount?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_ReviewCount!: () -> void

      def clear_ReviewCount_change: () -> void

      def ReviewCount_before_type_cast: () -> ::Integer

      def ReviewCount_for_database: () -> ::Integer

      def CreationTime: () -> ::ActiveSupport::TimeWithZone

      def CreationTime=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def CreationTime?: () -> bool

      def CreationTime_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def CreationTime_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def CreationTime_will_change!: () -> void

      def CreationTime_was: () -> ::ActiveSupport::TimeWithZone?

      def CreationTime_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def CreationTime_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def CreationTime_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def CreationTime_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def CreationTime_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def CreationTime_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_CreationTime: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_CreationTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_CreationTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_CreationTime!: () -> void

      def clear_CreationTime_change: () -> void

      def CreationTime_before_type_cast: () -> ::Time

      def CreationTime_for_database: () -> ::Time

      def CreatorUserId: () -> ::Integer?

      def CreatorUserId=: (::Integer?) -> ::Integer?

      def CreatorUserId?: () -> bool

      def CreatorUserId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def CreatorUserId_change: () -> [ ::Integer?, ::Integer? ]

      def CreatorUserId_will_change!: () -> void

      def CreatorUserId_was: () -> ::Integer?

      def CreatorUserId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def CreatorUserId_previous_change: () -> ::Array[::Integer?]?

      def CreatorUserId_previously_was: () -> ::Integer?

      def CreatorUserId_before_last_save: () -> ::Integer?

      def CreatorUserId_change_to_be_saved: () -> ::Array[::Integer?]?

      def CreatorUserId_in_database: () -> ::Integer?

      def saved_change_to_CreatorUserId: () -> ::Array[::Integer?]?

      def saved_change_to_CreatorUserId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_CreatorUserId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_CreatorUserId!: () -> void

      def clear_CreatorUserId_change: () -> void

      def CreatorUserId_before_type_cast: () -> ::Integer?

      def CreatorUserId_for_database: () -> ::Integer?

      def DeleterUserId: () -> ::Integer?

      def DeleterUserId=: (::Integer?) -> ::Integer?

      def DeleterUserId?: () -> bool

      def DeleterUserId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def DeleterUserId_change: () -> [ ::Integer?, ::Integer? ]

      def DeleterUserId_will_change!: () -> void

      def DeleterUserId_was: () -> ::Integer?

      def DeleterUserId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def DeleterUserId_previous_change: () -> ::Array[::Integer?]?

      def DeleterUserId_previously_was: () -> ::Integer?

      def DeleterUserId_before_last_save: () -> ::Integer?

      def DeleterUserId_change_to_be_saved: () -> ::Array[::Integer?]?

      def DeleterUserId_in_database: () -> ::Integer?

      def saved_change_to_DeleterUserId: () -> ::Array[::Integer?]?

      def saved_change_to_DeleterUserId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_DeleterUserId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_DeleterUserId!: () -> void

      def clear_DeleterUserId_change: () -> void

      def DeleterUserId_before_type_cast: () -> ::Integer?

      def DeleterUserId_for_database: () -> ::Integer?

      def DeletionTime: () -> ::ActiveSupport::TimeWithZone?

      def DeletionTime=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

      def DeletionTime?: () -> bool

      def DeletionTime_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def DeletionTime_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def DeletionTime_will_change!: () -> void

      def DeletionTime_was: () -> ::ActiveSupport::TimeWithZone?

      def DeletionTime_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def DeletionTime_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def DeletionTime_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def DeletionTime_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def DeletionTime_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def DeletionTime_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_DeletionTime: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_DeletionTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_DeletionTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_DeletionTime!: () -> void

      def clear_DeletionTime_change: () -> void

      def DeletionTime_before_type_cast: () -> ::Time?

      def DeletionTime_for_database: () -> ::Time?

      def IsDeleted: () -> bool

      def IsDeleted=: (bool) -> bool

      def IsDeleted?: () -> bool

      def IsDeleted_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsDeleted_change: () -> [ bool?, bool? ]

      def IsDeleted_will_change!: () -> void

      def IsDeleted_was: () -> bool?

      def IsDeleted_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsDeleted_previous_change: () -> ::Array[bool?]?

      def IsDeleted_previously_was: () -> bool?

      def IsDeleted_before_last_save: () -> bool?

      def IsDeleted_change_to_be_saved: () -> ::Array[bool?]?

      def IsDeleted_in_database: () -> bool?

      def saved_change_to_IsDeleted: () -> ::Array[bool?]?

      def saved_change_to_IsDeleted?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_IsDeleted?: (?from: bool?, ?to: bool?) -> bool

      def restore_IsDeleted!: () -> void

      def clear_IsDeleted_change: () -> void

      def IsDeleted_before_type_cast: () -> bool

      def IsDeleted_for_database: () -> bool

      def LastModificationTime: () -> ::ActiveSupport::TimeWithZone?

      def LastModificationTime=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

      def LastModificationTime?: () -> bool

      def LastModificationTime_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def LastModificationTime_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def LastModificationTime_will_change!: () -> void

      def LastModificationTime_was: () -> ::ActiveSupport::TimeWithZone?

      def LastModificationTime_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def LastModificationTime_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def LastModificationTime_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def LastModificationTime_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def LastModificationTime_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def LastModificationTime_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_LastModificationTime: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_LastModificationTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_LastModificationTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_LastModificationTime!: () -> void

      def clear_LastModificationTime_change: () -> void

      def LastModificationTime_before_type_cast: () -> ::Time?

      def LastModificationTime_for_database: () -> ::Time?

      def LastModifierUserId: () -> ::Integer?

      def LastModifierUserId=: (::Integer?) -> ::Integer?

      def LastModifierUserId?: () -> bool

      def LastModifierUserId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def LastModifierUserId_change: () -> [ ::Integer?, ::Integer? ]

      def LastModifierUserId_will_change!: () -> void

      def LastModifierUserId_was: () -> ::Integer?

      def LastModifierUserId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def LastModifierUserId_previous_change: () -> ::Array[::Integer?]?

      def LastModifierUserId_previously_was: () -> ::Integer?

      def LastModifierUserId_before_last_save: () -> ::Integer?

      def LastModifierUserId_change_to_be_saved: () -> ::Array[::Integer?]?

      def LastModifierUserId_in_database: () -> ::Integer?

      def saved_change_to_LastModifierUserId: () -> ::Array[::Integer?]?

      def saved_change_to_LastModifierUserId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_LastModifierUserId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_LastModifierUserId!: () -> void

      def clear_LastModifierUserId_change: () -> void

      def LastModifierUserId_before_type_cast: () -> ::Integer?

      def LastModifierUserId_for_database: () -> ::Integer?

      def EmployeeStatusRefValue: () -> ::String?

      def EmployeeStatusRefValue=: (::String?) -> ::String?

      def EmployeeStatusRefValue?: () -> bool

      def EmployeeStatusRefValue_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def EmployeeStatusRefValue_change: () -> [ ::String?, ::String? ]

      def EmployeeStatusRefValue_will_change!: () -> void

      def EmployeeStatusRefValue_was: () -> ::String?

      def EmployeeStatusRefValue_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def EmployeeStatusRefValue_previous_change: () -> ::Array[::String?]?

      def EmployeeStatusRefValue_previously_was: () -> ::String?

      def EmployeeStatusRefValue_before_last_save: () -> ::String?

      def EmployeeStatusRefValue_change_to_be_saved: () -> ::Array[::String?]?

      def EmployeeStatusRefValue_in_database: () -> ::String?

      def saved_change_to_EmployeeStatusRefValue: () -> ::Array[::String?]?

      def saved_change_to_EmployeeStatusRefValue?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_EmployeeStatusRefValue?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_EmployeeStatusRefValue!: () -> void

      def clear_EmployeeStatusRefValue_change: () -> void

      def EmployeeStatusRefValue_before_type_cast: () -> ::String?

      def EmployeeStatusRefValue_for_database: () -> ::String?

      def EmployeeTypeRefValue: () -> ::String?

      def EmployeeTypeRefValue=: (::String?) -> ::String?

      def EmployeeTypeRefValue?: () -> bool

      def EmployeeTypeRefValue_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def EmployeeTypeRefValue_change: () -> [ ::String?, ::String? ]

      def EmployeeTypeRefValue_will_change!: () -> void

      def EmployeeTypeRefValue_was: () -> ::String?

      def EmployeeTypeRefValue_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def EmployeeTypeRefValue_previous_change: () -> ::Array[::String?]?

      def EmployeeTypeRefValue_previously_was: () -> ::String?

      def EmployeeTypeRefValue_before_last_save: () -> ::String?

      def EmployeeTypeRefValue_change_to_be_saved: () -> ::Array[::String?]?

      def EmployeeTypeRefValue_in_database: () -> ::String?

      def saved_change_to_EmployeeTypeRefValue: () -> ::Array[::String?]?

      def saved_change_to_EmployeeTypeRefValue?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_EmployeeTypeRefValue?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_EmployeeTypeRefValue!: () -> void

      def clear_EmployeeTypeRefValue_change: () -> void

      def EmployeeTypeRefValue_before_type_cast: () -> ::String?

      def EmployeeTypeRefValue_for_database: () -> ::String?

      def StaffUnit: () -> ::BigDecimal

      def StaffUnit=: (::BigDecimal) -> ::BigDecimal

      def StaffUnit?: () -> bool

      def StaffUnit_changed?: (?from: ::BigDecimal?, ?to: ::BigDecimal?) -> bool

      def StaffUnit_change: () -> [ ::BigDecimal?, ::BigDecimal? ]

      def StaffUnit_will_change!: () -> void

      def StaffUnit_was: () -> ::BigDecimal?

      def StaffUnit_previously_changed?: (?from: ::BigDecimal?, ?to: ::BigDecimal?) -> bool

      def StaffUnit_previous_change: () -> ::Array[::BigDecimal?]?

      def StaffUnit_previously_was: () -> ::BigDecimal?

      def StaffUnit_before_last_save: () -> ::BigDecimal?

      def StaffUnit_change_to_be_saved: () -> ::Array[::BigDecimal?]?

      def StaffUnit_in_database: () -> ::BigDecimal?

      def saved_change_to_StaffUnit: () -> ::Array[::BigDecimal?]?

      def saved_change_to_StaffUnit?: (?from: ::BigDecimal?, ?to: ::BigDecimal?) -> bool

      def will_save_change_to_StaffUnit?: (?from: ::BigDecimal?, ?to: ::BigDecimal?) -> bool

      def restore_StaffUnit!: () -> void

      def clear_StaffUnit_change: () -> void

      def StaffUnit_before_type_cast: () -> ::BigDecimal

      def StaffUnit_for_database: () -> ::BigDecimal

      def ExternalId: () -> ::String?

      def ExternalId=: (::String?) -> ::String?

      def ExternalId?: () -> bool

      def ExternalId_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def ExternalId_change: () -> [ ::String?, ::String? ]

      def ExternalId_will_change!: () -> void

      def ExternalId_was: () -> ::String?

      def ExternalId_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def ExternalId_previous_change: () -> ::Array[::String?]?

      def ExternalId_previously_was: () -> ::String?

      def ExternalId_before_last_save: () -> ::String?

      def ExternalId_change_to_be_saved: () -> ::Array[::String?]?

      def ExternalId_in_database: () -> ::String?

      def saved_change_to_ExternalId: () -> ::Array[::String?]?

      def saved_change_to_ExternalId?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_ExternalId?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_ExternalId!: () -> void

      def clear_ExternalId_change: () -> void

      def ExternalId_before_type_cast: () -> ::String?

      def ExternalId_for_database: () -> ::String?

      def ExternalType: () -> ::String?

      def ExternalType=: (::String?) -> ::String?

      def ExternalType?: () -> bool

      def ExternalType_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def ExternalType_change: () -> [ ::String?, ::String? ]

      def ExternalType_will_change!: () -> void

      def ExternalType_was: () -> ::String?

      def ExternalType_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def ExternalType_previous_change: () -> ::Array[::String?]?

      def ExternalType_previously_was: () -> ::String?

      def ExternalType_before_last_save: () -> ::String?

      def ExternalType_change_to_be_saved: () -> ::Array[::String?]?

      def ExternalType_in_database: () -> ::String?

      def saved_change_to_ExternalType: () -> ::Array[::String?]?

      def saved_change_to_ExternalType?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_ExternalType?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_ExternalType!: () -> void

      def clear_ExternalType_change: () -> void

      def ExternalType_before_type_cast: () -> ::String?

      def ExternalType_for_database: () -> ::String?

      def InternalId: () -> ::String

      def InternalId=: (::String) -> ::String

      def InternalId?: () -> bool

      def InternalId_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def InternalId_change: () -> [ ::String?, ::String? ]

      def InternalId_will_change!: () -> void

      def InternalId_was: () -> ::String?

      def InternalId_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def InternalId_previous_change: () -> ::Array[::String?]?

      def InternalId_previously_was: () -> ::String?

      def InternalId_before_last_save: () -> ::String?

      def InternalId_change_to_be_saved: () -> ::Array[::String?]?

      def InternalId_in_database: () -> ::String?

      def saved_change_to_InternalId: () -> ::Array[::String?]?

      def saved_change_to_InternalId?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_InternalId?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_InternalId!: () -> void

      def clear_InternalId_change: () -> void

      def InternalId_before_type_cast: () -> ::String

      def InternalId_for_database: () -> ::String

      def AcceptsDeclarations: () -> bool

      def AcceptsDeclarations=: (bool) -> bool

      def AcceptsDeclarations?: () -> bool

      def AcceptsDeclarations_changed?: (?from: bool?, ?to: bool?) -> bool

      def AcceptsDeclarations_change: () -> [ bool?, bool? ]

      def AcceptsDeclarations_will_change!: () -> void

      def AcceptsDeclarations_was: () -> bool?

      def AcceptsDeclarations_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def AcceptsDeclarations_previous_change: () -> ::Array[bool?]?

      def AcceptsDeclarations_previously_was: () -> bool?

      def AcceptsDeclarations_before_last_save: () -> bool?

      def AcceptsDeclarations_change_to_be_saved: () -> ::Array[bool?]?

      def AcceptsDeclarations_in_database: () -> bool?

      def saved_change_to_AcceptsDeclarations: () -> ::Array[bool?]?

      def saved_change_to_AcceptsDeclarations?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_AcceptsDeclarations?: (?from: bool?, ?to: bool?) -> bool

      def restore_AcceptsDeclarations!: () -> void

      def clear_AcceptsDeclarations_change: () -> void

      def AcceptsDeclarations_before_type_cast: () -> bool

      def AcceptsDeclarations_for_database: () -> bool

      def IsHealth24: () -> bool

      def IsHealth24=: (bool) -> bool

      def IsHealth24?: () -> bool

      def IsHealth24_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsHealth24_change: () -> [ bool?, bool? ]

      def IsHealth24_will_change!: () -> void

      def IsHealth24_was: () -> bool?

      def IsHealth24_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsHealth24_previous_change: () -> ::Array[bool?]?

      def IsHealth24_previously_was: () -> bool?

      def IsHealth24_before_last_save: () -> bool?

      def IsHealth24_change_to_be_saved: () -> ::Array[bool?]?

      def IsHealth24_in_database: () -> bool?

      def saved_change_to_IsHealth24: () -> ::Array[bool?]?

      def saved_change_to_IsHealth24?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_IsHealth24?: (?from: bool?, ?to: bool?) -> bool

      def restore_IsHealth24!: () -> void

      def clear_IsHealth24_change: () -> void

      def IsHealth24_before_type_cast: () -> bool

      def IsHealth24_for_database: () -> bool

      def PositionTitle: () -> ::String?

      def PositionTitle=: (::String?) -> ::String?

      def PositionTitle?: () -> bool

      def PositionTitle_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def PositionTitle_change: () -> [ ::String?, ::String? ]

      def PositionTitle_will_change!: () -> void

      def PositionTitle_was: () -> ::String?

      def PositionTitle_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def PositionTitle_previous_change: () -> ::Array[::String?]?

      def PositionTitle_previously_was: () -> ::String?

      def PositionTitle_before_last_save: () -> ::String?

      def PositionTitle_change_to_be_saved: () -> ::Array[::String?]?

      def PositionTitle_in_database: () -> ::String?

      def saved_change_to_PositionTitle: () -> ::Array[::String?]?

      def saved_change_to_PositionTitle?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_PositionTitle?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_PositionTitle!: () -> void

      def clear_PositionTitle_change: () -> void

      def PositionTitle_before_type_cast: () -> ::String?

      def PositionTitle_for_database: () -> ::String?

      def NationalScreening: () -> bool

      def NationalScreening=: (bool) -> bool

      def NationalScreening?: () -> bool

      def NationalScreening_changed?: (?from: bool?, ?to: bool?) -> bool

      def NationalScreening_change: () -> [ bool?, bool? ]

      def NationalScreening_will_change!: () -> void

      def NationalScreening_was: () -> bool?

      def NationalScreening_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def NationalScreening_previous_change: () -> ::Array[bool?]?

      def NationalScreening_previously_was: () -> bool?

      def NationalScreening_before_last_save: () -> bool?

      def NationalScreening_change_to_be_saved: () -> ::Array[bool?]?

      def NationalScreening_in_database: () -> bool?

      def saved_change_to_NationalScreening: () -> ::Array[bool?]?

      def saved_change_to_NationalScreening?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_NationalScreening?: (?from: bool?, ?to: bool?) -> bool

      def restore_NationalScreening!: () -> void

      def clear_NationalScreening_change: () -> void

      def NationalScreening_before_type_cast: () -> bool

      def NationalScreening_for_database: () -> bool

      def ResourceOffice: () -> bool

      def ResourceOffice=: (bool) -> bool

      def ResourceOffice?: () -> bool

      def ResourceOffice_changed?: (?from: bool?, ?to: bool?) -> bool

      def ResourceOffice_change: () -> [ bool?, bool? ]

      def ResourceOffice_will_change!: () -> void

      def ResourceOffice_was: () -> bool?

      def ResourceOffice_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def ResourceOffice_previous_change: () -> ::Array[bool?]?

      def ResourceOffice_previously_was: () -> bool?

      def ResourceOffice_before_last_save: () -> bool?

      def ResourceOffice_change_to_be_saved: () -> ::Array[bool?]?

      def ResourceOffice_in_database: () -> bool?

      def saved_change_to_ResourceOffice: () -> ::Array[bool?]?

      def saved_change_to_ResourceOffice?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_ResourceOffice?: (?from: bool?, ?to: bool?) -> bool

      def restore_ResourceOffice!: () -> void

      def clear_ResourceOffice_change: () -> void

      def ResourceOffice_before_type_cast: () -> bool

      def ResourceOffice_for_database: () -> bool
    end
    include ::H24Auth::Employee::GeneratedAttributeMethods
    module ::H24Auth::Employee::GeneratedAliasAttributeMethods
      include ::H24Auth::Employee::GeneratedAttributeMethods
    end
    include ::H24Auth::Employee::GeneratedAliasAttributeMethods

    module ::H24Auth::Employee::GeneratedAssociationMethods
    end
    include ::H24Auth::Employee::GeneratedAssociationMethods

    module ::H24Auth::Employee::GeneratedRelationMethods
    end

    class ::H24Auth::Employee::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::H24Auth::Employee]
      include ::H24Auth::Employee::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::H24Auth::Employee, ::Integer]
    end

    class ::H24Auth::Employee::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::H24Auth::Employee]
      include ::H24Auth::Employee::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::H24Auth::Employee, ::Integer]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::H24Auth::Employee
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::H24Auth::Employee]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::H24Auth::Employee
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::H24Auth::Employee]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::H24Auth::Employee
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::H24Auth::Employee]
      def reload: () -> ::Array[::H24Auth::Employee]

      def replace: (::Array[::H24Auth::Employee]) -> void
      def delete: (*::H24Auth::Employee | ::Integer) -> ::Array[::H24Auth::Employee]
      def destroy: (*::H24Auth::Employee | ::Integer) -> ::Array[::H24Auth::Employee]
      def <<: (*::H24Auth::Employee | ::Array[::H24Auth::Employee]) -> self
      def prepend: (*::H24Auth::Employee | ::Array[::H24Auth::Employee]) -> self
    end
  end
end

module ::H24Auth
end
class ::H24Auth::ApplicationRecord < ::ActiveRecord::Base
end
