# resolve-type-names: false

module ::H24Auth
  class ::H24Auth::Party < ::H24Auth::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::H24Auth::Party, ::H24Auth::Party::ActiveRecord_Relation, ::Integer]

    module ::H24Auth::Party::GeneratedAttributeMethods
      def Id: () -> ::Integer

      def Id=: (::Integer) -> ::Integer

      def Id?: () -> bool

      def Id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def Id_change: () -> [ ::Integer?, ::Integer? ]

      def Id_will_change!: () -> void

      def Id_was: () -> ::Integer?

      def Id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def Id_previous_change: () -> ::Array[::Integer?]?

      def Id_previously_was: () -> ::Integer?

      def Id_before_last_save: () -> ::Integer?

      def Id_change_to_be_saved: () -> ::Array[::Integer?]?

      def Id_in_database: () -> ::Integer?

      def saved_change_to_Id: () -> ::Array[::Integer?]?

      def saved_change_to_Id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_Id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_Id!: () -> void

      def clear_Id_change: () -> void

      def Id_before_type_cast: () -> ::Integer

      def Id_for_database: () -> ::Integer

      def FirstName: () -> ::String?

      def FirstName=: (::String?) -> ::String?

      def FirstName?: () -> bool

      def FirstName_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def FirstName_change: () -> [ ::String?, ::String? ]

      def FirstName_will_change!: () -> void

      def FirstName_was: () -> ::String?

      def FirstName_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def FirstName_previous_change: () -> ::Array[::String?]?

      def FirstName_previously_was: () -> ::String?

      def FirstName_before_last_save: () -> ::String?

      def FirstName_change_to_be_saved: () -> ::Array[::String?]?

      def FirstName_in_database: () -> ::String?

      def saved_change_to_FirstName: () -> ::Array[::String?]?

      def saved_change_to_FirstName?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_FirstName?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_FirstName!: () -> void

      def clear_FirstName_change: () -> void

      def FirstName_before_type_cast: () -> ::String?

      def FirstName_for_database: () -> ::String?

      def LastName: () -> ::String?

      def LastName=: (::String?) -> ::String?

      def LastName?: () -> bool

      def LastName_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def LastName_change: () -> [ ::String?, ::String? ]

      def LastName_will_change!: () -> void

      def LastName_was: () -> ::String?

      def LastName_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def LastName_previous_change: () -> ::Array[::String?]?

      def LastName_previously_was: () -> ::String?

      def LastName_before_last_save: () -> ::String?

      def LastName_change_to_be_saved: () -> ::Array[::String?]?

      def LastName_in_database: () -> ::String?

      def saved_change_to_LastName: () -> ::Array[::String?]?

      def saved_change_to_LastName?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_LastName?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_LastName!: () -> void

      def clear_LastName_change: () -> void

      def LastName_before_type_cast: () -> ::String?

      def LastName_for_database: () -> ::String?

      def SecondName: () -> ::String?

      def SecondName=: (::String?) -> ::String?

      def SecondName?: () -> bool

      def SecondName_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def SecondName_change: () -> [ ::String?, ::String? ]

      def SecondName_will_change!: () -> void

      def SecondName_was: () -> ::String?

      def SecondName_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def SecondName_previous_change: () -> ::Array[::String?]?

      def SecondName_previously_was: () -> ::String?

      def SecondName_before_last_save: () -> ::String?

      def SecondName_change_to_be_saved: () -> ::Array[::String?]?

      def SecondName_in_database: () -> ::String?

      def saved_change_to_SecondName: () -> ::Array[::String?]?

      def saved_change_to_SecondName?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_SecondName?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_SecondName!: () -> void

      def clear_SecondName_change: () -> void

      def SecondName_before_type_cast: () -> ::String?

      def SecondName_for_database: () -> ::String?

      def TaxId: () -> ::String?

      def TaxId=: (::String?) -> ::String?

      def TaxId?: () -> bool

      def TaxId_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def TaxId_change: () -> [ ::String?, ::String? ]

      def TaxId_will_change!: () -> void

      def TaxId_was: () -> ::String?

      def TaxId_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def TaxId_previous_change: () -> ::Array[::String?]?

      def TaxId_previously_was: () -> ::String?

      def TaxId_before_last_save: () -> ::String?

      def TaxId_change_to_be_saved: () -> ::Array[::String?]?

      def TaxId_in_database: () -> ::String?

      def saved_change_to_TaxId: () -> ::Array[::String?]?

      def saved_change_to_TaxId?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_TaxId?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_TaxId!: () -> void

      def clear_TaxId_change: () -> void

      def TaxId_before_type_cast: () -> ::String?

      def TaxId_for_database: () -> ::String?

      def BirthDate: () -> ::Date?

      def BirthDate=: (::Date?) -> ::Date?

      def BirthDate?: () -> bool

      def BirthDate_changed?: (?from: ::Date?, ?to: ::Date?) -> bool

      def BirthDate_change: () -> [ ::Date?, ::Date? ]

      def BirthDate_will_change!: () -> void

      def BirthDate_was: () -> ::Date?

      def BirthDate_previously_changed?: (?from: ::Date?, ?to: ::Date?) -> bool

      def BirthDate_previous_change: () -> ::Array[::Date?]?

      def BirthDate_previously_was: () -> ::Date?

      def BirthDate_before_last_save: () -> ::Date?

      def BirthDate_change_to_be_saved: () -> ::Array[::Date?]?

      def BirthDate_in_database: () -> ::Date?

      def saved_change_to_BirthDate: () -> ::Array[::Date?]?

      def saved_change_to_BirthDate?: (?from: ::Date?, ?to: ::Date?) -> bool

      def will_save_change_to_BirthDate?: (?from: ::Date?, ?to: ::Date?) -> bool

      def restore_BirthDate!: () -> void

      def clear_BirthDate_change: () -> void

      def BirthDate_before_type_cast: () -> ::Date?

      def BirthDate_for_database: () -> ::Date?

      def BirthPlace: () -> ::String?

      def BirthPlace=: (::String?) -> ::String?

      def BirthPlace?: () -> bool

      def BirthPlace_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def BirthPlace_change: () -> [ ::String?, ::String? ]

      def BirthPlace_will_change!: () -> void

      def BirthPlace_was: () -> ::String?

      def BirthPlace_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def BirthPlace_previous_change: () -> ::Array[::String?]?

      def BirthPlace_previously_was: () -> ::String?

      def BirthPlace_before_last_save: () -> ::String?

      def BirthPlace_change_to_be_saved: () -> ::Array[::String?]?

      def BirthPlace_in_database: () -> ::String?

      def saved_change_to_BirthPlace: () -> ::Array[::String?]?

      def saved_change_to_BirthPlace?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_BirthPlace?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_BirthPlace!: () -> void

      def clear_BirthPlace_change: () -> void

      def BirthPlace_before_type_cast: () -> ::String?

      def BirthPlace_for_database: () -> ::String?

      def GenderRefId: () -> ::Integer?

      def GenderRefId=: (::Integer?) -> ::Integer?

      def GenderRefId?: () -> bool

      def GenderRefId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def GenderRefId_change: () -> [ ::Integer?, ::Integer? ]

      def GenderRefId_will_change!: () -> void

      def GenderRefId_was: () -> ::Integer?

      def GenderRefId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def GenderRefId_previous_change: () -> ::Array[::Integer?]?

      def GenderRefId_previously_was: () -> ::Integer?

      def GenderRefId_before_last_save: () -> ::Integer?

      def GenderRefId_change_to_be_saved: () -> ::Array[::Integer?]?

      def GenderRefId_in_database: () -> ::Integer?

      def saved_change_to_GenderRefId: () -> ::Array[::Integer?]?

      def saved_change_to_GenderRefId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_GenderRefId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_GenderRefId!: () -> void

      def clear_GenderRefId_change: () -> void

      def GenderRefId_before_type_cast: () -> ::Integer?

      def GenderRefId_for_database: () -> ::Integer?

      def NoTaxId: () -> bool?

      def NoTaxId=: (bool?) -> bool?

      def NoTaxId?: () -> bool

      def NoTaxId_changed?: (?from: bool?, ?to: bool?) -> bool

      def NoTaxId_change: () -> [ bool?, bool? ]

      def NoTaxId_will_change!: () -> void

      def NoTaxId_was: () -> bool?

      def NoTaxId_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def NoTaxId_previous_change: () -> ::Array[bool?]?

      def NoTaxId_previously_was: () -> bool?

      def NoTaxId_before_last_save: () -> bool?

      def NoTaxId_change_to_be_saved: () -> ::Array[bool?]?

      def NoTaxId_in_database: () -> bool?

      def saved_change_to_NoTaxId: () -> ::Array[bool?]?

      def saved_change_to_NoTaxId?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_NoTaxId?: (?from: bool?, ?to: bool?) -> bool

      def restore_NoTaxId!: () -> void

      def clear_NoTaxId_change: () -> void

      def NoTaxId_before_type_cast: () -> bool?

      def NoTaxId_for_database: () -> bool?

      def WorkingExperience: () -> ::Integer?

      def WorkingExperience=: (::Integer?) -> ::Integer?

      def WorkingExperience?: () -> bool

      def WorkingExperience_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def WorkingExperience_change: () -> [ ::Integer?, ::Integer? ]

      def WorkingExperience_will_change!: () -> void

      def WorkingExperience_was: () -> ::Integer?

      def WorkingExperience_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def WorkingExperience_previous_change: () -> ::Array[::Integer?]?

      def WorkingExperience_previously_was: () -> ::Integer?

      def WorkingExperience_before_last_save: () -> ::Integer?

      def WorkingExperience_change_to_be_saved: () -> ::Array[::Integer?]?

      def WorkingExperience_in_database: () -> ::Integer?

      def saved_change_to_WorkingExperience: () -> ::Array[::Integer?]?

      def saved_change_to_WorkingExperience?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_WorkingExperience?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_WorkingExperience!: () -> void

      def clear_WorkingExperience_change: () -> void

      def WorkingExperience_before_type_cast: () -> ::Integer?

      def WorkingExperience_for_database: () -> ::Integer?

      def AboutMyself: () -> ::String?

      def AboutMyself=: (::String?) -> ::String?

      def AboutMyself?: () -> bool

      def AboutMyself_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def AboutMyself_change: () -> [ ::String?, ::String? ]

      def AboutMyself_will_change!: () -> void

      def AboutMyself_was: () -> ::String?

      def AboutMyself_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def AboutMyself_previous_change: () -> ::Array[::String?]?

      def AboutMyself_previously_was: () -> ::String?

      def AboutMyself_before_last_save: () -> ::String?

      def AboutMyself_change_to_be_saved: () -> ::Array[::String?]?

      def AboutMyself_in_database: () -> ::String?

      def saved_change_to_AboutMyself: () -> ::Array[::String?]?

      def saved_change_to_AboutMyself?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_AboutMyself?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_AboutMyself!: () -> void

      def clear_AboutMyself_change: () -> void

      def AboutMyself_before_type_cast: () -> ::String?

      def AboutMyself_for_database: () -> ::String?

      def LegalEntityId: () -> ::Integer

      def LegalEntityId=: (::Integer) -> ::Integer

      def LegalEntityId?: () -> bool

      def LegalEntityId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def LegalEntityId_change: () -> [ ::Integer?, ::Integer? ]

      def LegalEntityId_will_change!: () -> void

      def LegalEntityId_was: () -> ::Integer?

      def LegalEntityId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def LegalEntityId_previous_change: () -> ::Array[::Integer?]?

      def LegalEntityId_previously_was: () -> ::Integer?

      def LegalEntityId_before_last_save: () -> ::Integer?

      def LegalEntityId_change_to_be_saved: () -> ::Array[::Integer?]?

      def LegalEntityId_in_database: () -> ::Integer?

      def saved_change_to_LegalEntityId: () -> ::Array[::Integer?]?

      def saved_change_to_LegalEntityId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_LegalEntityId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_LegalEntityId!: () -> void

      def clear_LegalEntityId_change: () -> void

      def LegalEntityId_before_type_cast: () -> ::Integer

      def LegalEntityId_for_database: () -> ::Integer

      def UserId: () -> ::Integer?

      def UserId=: (::Integer?) -> ::Integer?

      def UserId?: () -> bool

      def UserId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def UserId_change: () -> [ ::Integer?, ::Integer? ]

      def UserId_will_change!: () -> void

      def UserId_was: () -> ::Integer?

      def UserId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def UserId_previous_change: () -> ::Array[::Integer?]?

      def UserId_previously_was: () -> ::Integer?

      def UserId_before_last_save: () -> ::Integer?

      def UserId_change_to_be_saved: () -> ::Array[::Integer?]?

      def UserId_in_database: () -> ::Integer?

      def saved_change_to_UserId: () -> ::Array[::Integer?]?

      def saved_change_to_UserId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_UserId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_UserId!: () -> void

      def clear_UserId_change: () -> void

      def UserId_before_type_cast: () -> ::Integer?

      def UserId_for_database: () -> ::Integer?

      def Email: () -> ::String?

      def Email=: (::String?) -> ::String?

      def Email?: () -> bool

      def Email_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def Email_change: () -> [ ::String?, ::String? ]

      def Email_will_change!: () -> void

      def Email_was: () -> ::String?

      def Email_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def Email_previous_change: () -> ::Array[::String?]?

      def Email_previously_was: () -> ::String?

      def Email_before_last_save: () -> ::String?

      def Email_change_to_be_saved: () -> ::Array[::String?]?

      def Email_in_database: () -> ::String?

      def saved_change_to_Email: () -> ::Array[::String?]?

      def saved_change_to_Email?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_Email?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_Email!: () -> void

      def clear_Email_change: () -> void

      def Email_before_type_cast: () -> ::String?

      def Email_for_database: () -> ::String?

      def OldPartyId: () -> ::Integer?

      def OldPartyId=: (::Integer?) -> ::Integer?

      def OldPartyId?: () -> bool

      def OldPartyId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def OldPartyId_change: () -> [ ::Integer?, ::Integer? ]

      def OldPartyId_will_change!: () -> void

      def OldPartyId_was: () -> ::Integer?

      def OldPartyId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def OldPartyId_previous_change: () -> ::Array[::Integer?]?

      def OldPartyId_previously_was: () -> ::Integer?

      def OldPartyId_before_last_save: () -> ::Integer?

      def OldPartyId_change_to_be_saved: () -> ::Array[::Integer?]?

      def OldPartyId_in_database: () -> ::Integer?

      def saved_change_to_OldPartyId: () -> ::Array[::Integer?]?

      def saved_change_to_OldPartyId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_OldPartyId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_OldPartyId!: () -> void

      def clear_OldPartyId_change: () -> void

      def OldPartyId_before_type_cast: () -> ::Integer?

      def OldPartyId_for_database: () -> ::Integer?

      def IsOnPortal: () -> bool

      def IsOnPortal=: (bool) -> bool

      def IsOnPortal?: () -> bool

      def IsOnPortal_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsOnPortal_change: () -> [ bool?, bool? ]

      def IsOnPortal_will_change!: () -> void

      def IsOnPortal_was: () -> bool?

      def IsOnPortal_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsOnPortal_previous_change: () -> ::Array[bool?]?

      def IsOnPortal_previously_was: () -> bool?

      def IsOnPortal_before_last_save: () -> bool?

      def IsOnPortal_change_to_be_saved: () -> ::Array[bool?]?

      def IsOnPortal_in_database: () -> bool?

      def saved_change_to_IsOnPortal: () -> ::Array[bool?]?

      def saved_change_to_IsOnPortal?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_IsOnPortal?: (?from: bool?, ?to: bool?) -> bool

      def restore_IsOnPortal!: () -> void

      def clear_IsOnPortal_change: () -> void

      def IsOnPortal_before_type_cast: () -> bool

      def IsOnPortal_for_database: () -> bool

      def Rating: () -> ::Float?

      def Rating=: (::Float?) -> ::Float?

      def Rating?: () -> bool

      def Rating_changed?: (?from: ::Float?, ?to: ::Float?) -> bool

      def Rating_change: () -> [ ::Float?, ::Float? ]

      def Rating_will_change!: () -> void

      def Rating_was: () -> ::Float?

      def Rating_previously_changed?: (?from: ::Float?, ?to: ::Float?) -> bool

      def Rating_previous_change: () -> ::Array[::Float?]?

      def Rating_previously_was: () -> ::Float?

      def Rating_before_last_save: () -> ::Float?

      def Rating_change_to_be_saved: () -> ::Array[::Float?]?

      def Rating_in_database: () -> ::Float?

      def saved_change_to_Rating: () -> ::Array[::Float?]?

      def saved_change_to_Rating?: (?from: ::Float?, ?to: ::Float?) -> bool

      def will_save_change_to_Rating?: (?from: ::Float?, ?to: ::Float?) -> bool

      def restore_Rating!: () -> void

      def clear_Rating_change: () -> void

      def Rating_before_type_cast: () -> ::Float?

      def Rating_for_database: () -> ::Float?

      def ReviewCount: () -> ::Integer

      def ReviewCount=: (::Integer) -> ::Integer

      def ReviewCount?: () -> bool

      def ReviewCount_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def ReviewCount_change: () -> [ ::Integer?, ::Integer? ]

      def ReviewCount_will_change!: () -> void

      def ReviewCount_was: () -> ::Integer?

      def ReviewCount_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def ReviewCount_previous_change: () -> ::Array[::Integer?]?

      def ReviewCount_previously_was: () -> ::Integer?

      def ReviewCount_before_last_save: () -> ::Integer?

      def ReviewCount_change_to_be_saved: () -> ::Array[::Integer?]?

      def ReviewCount_in_database: () -> ::Integer?

      def saved_change_to_ReviewCount: () -> ::Array[::Integer?]?

      def saved_change_to_ReviewCount?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_ReviewCount?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_ReviewCount!: () -> void

      def clear_ReviewCount_change: () -> void

      def ReviewCount_before_type_cast: () -> ::Integer

      def ReviewCount_for_database: () -> ::Integer

      def LogoId: () -> ::Integer?

      def LogoId=: (::Integer?) -> ::Integer?

      def LogoId?: () -> bool

      def LogoId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def LogoId_change: () -> [ ::Integer?, ::Integer? ]

      def LogoId_will_change!: () -> void

      def LogoId_was: () -> ::Integer?

      def LogoId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def LogoId_previous_change: () -> ::Array[::Integer?]?

      def LogoId_previously_was: () -> ::Integer?

      def LogoId_before_last_save: () -> ::Integer?

      def LogoId_change_to_be_saved: () -> ::Array[::Integer?]?

      def LogoId_in_database: () -> ::Integer?

      def saved_change_to_LogoId: () -> ::Array[::Integer?]?

      def saved_change_to_LogoId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_LogoId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_LogoId!: () -> void

      def clear_LogoId_change: () -> void

      def LogoId_before_type_cast: () -> ::Integer?

      def LogoId_for_database: () -> ::Integer?

      def HasContractWithH24: () -> bool

      def HasContractWithH24=: (bool) -> bool

      def HasContractWithH24?: () -> bool

      def HasContractWithH24_changed?: (?from: bool?, ?to: bool?) -> bool

      def HasContractWithH24_change: () -> [ bool?, bool? ]

      def HasContractWithH24_will_change!: () -> void

      def HasContractWithH24_was: () -> bool?

      def HasContractWithH24_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def HasContractWithH24_previous_change: () -> ::Array[bool?]?

      def HasContractWithH24_previously_was: () -> bool?

      def HasContractWithH24_before_last_save: () -> bool?

      def HasContractWithH24_change_to_be_saved: () -> ::Array[bool?]?

      def HasContractWithH24_in_database: () -> bool?

      def saved_change_to_HasContractWithH24: () -> ::Array[bool?]?

      def saved_change_to_HasContractWithH24?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_HasContractWithH24?: (?from: bool?, ?to: bool?) -> bool

      def restore_HasContractWithH24!: () -> void

      def clear_HasContractWithH24_change: () -> void

      def HasContractWithH24_before_type_cast: () -> bool

      def HasContractWithH24_for_database: () -> bool

      def IsTop: () -> bool

      def IsTop=: (bool) -> bool

      def IsTop?: () -> bool

      def IsTop_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsTop_change: () -> [ bool?, bool? ]

      def IsTop_will_change!: () -> void

      def IsTop_was: () -> bool?

      def IsTop_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsTop_previous_change: () -> ::Array[bool?]?

      def IsTop_previously_was: () -> bool?

      def IsTop_before_last_save: () -> bool?

      def IsTop_change_to_be_saved: () -> ::Array[bool?]?

      def IsTop_in_database: () -> bool?

      def saved_change_to_IsTop: () -> ::Array[bool?]?

      def saved_change_to_IsTop?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_IsTop?: (?from: bool?, ?to: bool?) -> bool

      def restore_IsTop!: () -> void

      def clear_IsTop_change: () -> void

      def IsTop_before_type_cast: () -> bool

      def IsTop_for_database: () -> bool

      def MembershipProfessionalCommunities: () -> ::String?

      def MembershipProfessionalCommunities=: (::String?) -> ::String?

      def MembershipProfessionalCommunities?: () -> bool

      def MembershipProfessionalCommunities_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def MembershipProfessionalCommunities_change: () -> [ ::String?, ::String? ]

      def MembershipProfessionalCommunities_will_change!: () -> void

      def MembershipProfessionalCommunities_was: () -> ::String?

      def MembershipProfessionalCommunities_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def MembershipProfessionalCommunities_previous_change: () -> ::Array[::String?]?

      def MembershipProfessionalCommunities_previously_was: () -> ::String?

      def MembershipProfessionalCommunities_before_last_save: () -> ::String?

      def MembershipProfessionalCommunities_change_to_be_saved: () -> ::Array[::String?]?

      def MembershipProfessionalCommunities_in_database: () -> ::String?

      def saved_change_to_MembershipProfessionalCommunities: () -> ::Array[::String?]?

      def saved_change_to_MembershipProfessionalCommunities?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_MembershipProfessionalCommunities?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_MembershipProfessionalCommunities!: () -> void

      def clear_MembershipProfessionalCommunities_change: () -> void

      def MembershipProfessionalCommunities_before_type_cast: () -> ::String?

      def MembershipProfessionalCommunities_for_database: () -> ::String?

      def WorkingExperienceDeskription: () -> ::String?

      def WorkingExperienceDeskription=: (::String?) -> ::String?

      def WorkingExperienceDeskription?: () -> bool

      def WorkingExperienceDeskription_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def WorkingExperienceDeskription_change: () -> [ ::String?, ::String? ]

      def WorkingExperienceDeskription_will_change!: () -> void

      def WorkingExperienceDeskription_was: () -> ::String?

      def WorkingExperienceDeskription_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def WorkingExperienceDeskription_previous_change: () -> ::Array[::String?]?

      def WorkingExperienceDeskription_previously_was: () -> ::String?

      def WorkingExperienceDeskription_before_last_save: () -> ::String?

      def WorkingExperienceDeskription_change_to_be_saved: () -> ::Array[::String?]?

      def WorkingExperienceDeskription_in_database: () -> ::String?

      def saved_change_to_WorkingExperienceDeskription: () -> ::Array[::String?]?

      def saved_change_to_WorkingExperienceDeskription?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_WorkingExperienceDeskription?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_WorkingExperienceDeskription!: () -> void

      def clear_WorkingExperienceDeskription_change: () -> void

      def WorkingExperienceDeskription_before_type_cast: () -> ::String?

      def WorkingExperienceDeskription_for_database: () -> ::String?

      def CreationTime: () -> ::ActiveSupport::TimeWithZone

      def CreationTime=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def CreationTime?: () -> bool

      def CreationTime_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def CreationTime_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def CreationTime_will_change!: () -> void

      def CreationTime_was: () -> ::ActiveSupport::TimeWithZone?

      def CreationTime_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def CreationTime_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def CreationTime_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def CreationTime_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def CreationTime_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def CreationTime_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_CreationTime: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_CreationTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_CreationTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_CreationTime!: () -> void

      def clear_CreationTime_change: () -> void

      def CreationTime_before_type_cast: () -> ::Time

      def CreationTime_for_database: () -> ::Time

      def Info: () -> ::String?

      def Info=: (::String?) -> ::String?

      def Info?: () -> bool

      def Info_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def Info_change: () -> [ ::String?, ::String? ]

      def Info_will_change!: () -> void

      def Info_was: () -> ::String?

      def Info_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def Info_previous_change: () -> ::Array[::String?]?

      def Info_previously_was: () -> ::String?

      def Info_before_last_save: () -> ::String?

      def Info_change_to_be_saved: () -> ::Array[::String?]?

      def Info_in_database: () -> ::String?

      def saved_change_to_Info: () -> ::Array[::String?]?

      def saved_change_to_Info?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_Info?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_Info!: () -> void

      def clear_Info_change: () -> void

      def Info_before_type_cast: () -> ::String?

      def Info_for_database: () -> ::String?

      def LastModificationTime: () -> ::ActiveSupport::TimeWithZone?

      def LastModificationTime=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

      def LastModificationTime?: () -> bool

      def LastModificationTime_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def LastModificationTime_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def LastModificationTime_will_change!: () -> void

      def LastModificationTime_was: () -> ::ActiveSupport::TimeWithZone?

      def LastModificationTime_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def LastModificationTime_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def LastModificationTime_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def LastModificationTime_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def LastModificationTime_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def LastModificationTime_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_LastModificationTime: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_LastModificationTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_LastModificationTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_LastModificationTime!: () -> void

      def clear_LastModificationTime_change: () -> void

      def LastModificationTime_before_type_cast: () -> ::Time?

      def LastModificationTime_for_database: () -> ::Time?

      def LastModifierUserId: () -> ::Integer?

      def LastModifierUserId=: (::Integer?) -> ::Integer?

      def LastModifierUserId?: () -> bool

      def LastModifierUserId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def LastModifierUserId_change: () -> [ ::Integer?, ::Integer? ]

      def LastModifierUserId_will_change!: () -> void

      def LastModifierUserId_was: () -> ::Integer?

      def LastModifierUserId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def LastModifierUserId_previous_change: () -> ::Array[::Integer?]?

      def LastModifierUserId_previously_was: () -> ::Integer?

      def LastModifierUserId_before_last_save: () -> ::Integer?

      def LastModifierUserId_change_to_be_saved: () -> ::Array[::Integer?]?

      def LastModifierUserId_in_database: () -> ::Integer?

      def saved_change_to_LastModifierUserId: () -> ::Array[::Integer?]?

      def saved_change_to_LastModifierUserId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_LastModifierUserId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_LastModifierUserId!: () -> void

      def clear_LastModifierUserId_change: () -> void

      def LastModifierUserId_before_type_cast: () -> ::Integer?

      def LastModifierUserId_for_database: () -> ::Integer?

      def FirstNameTranslations: () -> untyped

      def FirstNameTranslations=: (untyped) -> untyped

      def FirstNameTranslations?: () -> bool

      def FirstNameTranslations_changed?: (?from: untyped, ?to: untyped) -> bool

      def FirstNameTranslations_change: () -> [ untyped, untyped ]

      def FirstNameTranslations_will_change!: () -> void

      def FirstNameTranslations_was: () -> untyped

      def FirstNameTranslations_previously_changed?: (?from: untyped, ?to: untyped) -> bool

      def FirstNameTranslations_previous_change: () -> ::Array[untyped]?

      def FirstNameTranslations_previously_was: () -> untyped

      def FirstNameTranslations_before_last_save: () -> untyped

      def FirstNameTranslations_change_to_be_saved: () -> ::Array[untyped]?

      def FirstNameTranslations_in_database: () -> untyped

      def saved_change_to_FirstNameTranslations: () -> ::Array[untyped]?

      def saved_change_to_FirstNameTranslations?: (?from: untyped, ?to: untyped) -> bool

      def will_save_change_to_FirstNameTranslations?: (?from: untyped, ?to: untyped) -> bool

      def restore_FirstNameTranslations!: () -> void

      def clear_FirstNameTranslations_change: () -> void

      def FirstNameTranslations_before_type_cast: () -> untyped?

      def FirstNameTranslations_for_database: () -> untyped?

      def LastNameTranslations: () -> untyped

      def LastNameTranslations=: (untyped) -> untyped

      def LastNameTranslations?: () -> bool

      def LastNameTranslations_changed?: (?from: untyped, ?to: untyped) -> bool

      def LastNameTranslations_change: () -> [ untyped, untyped ]

      def LastNameTranslations_will_change!: () -> void

      def LastNameTranslations_was: () -> untyped

      def LastNameTranslations_previously_changed?: (?from: untyped, ?to: untyped) -> bool

      def LastNameTranslations_previous_change: () -> ::Array[untyped]?

      def LastNameTranslations_previously_was: () -> untyped

      def LastNameTranslations_before_last_save: () -> untyped

      def LastNameTranslations_change_to_be_saved: () -> ::Array[untyped]?

      def LastNameTranslations_in_database: () -> untyped

      def saved_change_to_LastNameTranslations: () -> ::Array[untyped]?

      def saved_change_to_LastNameTranslations?: (?from: untyped, ?to: untyped) -> bool

      def will_save_change_to_LastNameTranslations?: (?from: untyped, ?to: untyped) -> bool

      def restore_LastNameTranslations!: () -> void

      def clear_LastNameTranslations_change: () -> void

      def LastNameTranslations_before_type_cast: () -> untyped?

      def LastNameTranslations_for_database: () -> untyped?

      def MembershipProfessionalCommunitiesTranslations: () -> untyped

      def MembershipProfessionalCommunitiesTranslations=: (untyped) -> untyped

      def MembershipProfessionalCommunitiesTranslations?: () -> bool

      def MembershipProfessionalCommunitiesTranslations_changed?: (?from: untyped, ?to: untyped) -> bool

      def MembershipProfessionalCommunitiesTranslations_change: () -> [ untyped, untyped ]

      def MembershipProfessionalCommunitiesTranslations_will_change!: () -> void

      def MembershipProfessionalCommunitiesTranslations_was: () -> untyped

      def MembershipProfessionalCommunitiesTranslations_previously_changed?: (?from: untyped, ?to: untyped) -> bool

      def MembershipProfessionalCommunitiesTranslations_previous_change: () -> ::Array[untyped]?

      def MembershipProfessionalCommunitiesTranslations_previously_was: () -> untyped

      def MembershipProfessionalCommunitiesTranslations_before_last_save: () -> untyped

      def MembershipProfessionalCommunitiesTranslations_change_to_be_saved: () -> ::Array[untyped]?

      def MembershipProfessionalCommunitiesTranslations_in_database: () -> untyped

      def saved_change_to_MembershipProfessionalCommunitiesTranslations: () -> ::Array[untyped]?

      def saved_change_to_MembershipProfessionalCommunitiesTranslations?: (?from: untyped, ?to: untyped) -> bool

      def will_save_change_to_MembershipProfessionalCommunitiesTranslations?: (?from: untyped, ?to: untyped) -> bool

      def restore_MembershipProfessionalCommunitiesTranslations!: () -> void

      def clear_MembershipProfessionalCommunitiesTranslations_change: () -> void

      def MembershipProfessionalCommunitiesTranslations_before_type_cast: () -> untyped?

      def MembershipProfessionalCommunitiesTranslations_for_database: () -> untyped?

      def SecondNameTranslations: () -> untyped

      def SecondNameTranslations=: (untyped) -> untyped

      def SecondNameTranslations?: () -> bool

      def SecondNameTranslations_changed?: (?from: untyped, ?to: untyped) -> bool

      def SecondNameTranslations_change: () -> [ untyped, untyped ]

      def SecondNameTranslations_will_change!: () -> void

      def SecondNameTranslations_was: () -> untyped

      def SecondNameTranslations_previously_changed?: (?from: untyped, ?to: untyped) -> bool

      def SecondNameTranslations_previous_change: () -> ::Array[untyped]?

      def SecondNameTranslations_previously_was: () -> untyped

      def SecondNameTranslations_before_last_save: () -> untyped

      def SecondNameTranslations_change_to_be_saved: () -> ::Array[untyped]?

      def SecondNameTranslations_in_database: () -> untyped

      def saved_change_to_SecondNameTranslations: () -> ::Array[untyped]?

      def saved_change_to_SecondNameTranslations?: (?from: untyped, ?to: untyped) -> bool

      def will_save_change_to_SecondNameTranslations?: (?from: untyped, ?to: untyped) -> bool

      def restore_SecondNameTranslations!: () -> void

      def clear_SecondNameTranslations_change: () -> void

      def SecondNameTranslations_before_type_cast: () -> untyped?

      def SecondNameTranslations_for_database: () -> untyped?

      def LastSlugModificationTime: () -> ::ActiveSupport::TimeWithZone?

      def LastSlugModificationTime=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

      def LastSlugModificationTime?: () -> bool

      def LastSlugModificationTime_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def LastSlugModificationTime_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def LastSlugModificationTime_will_change!: () -> void

      def LastSlugModificationTime_was: () -> ::ActiveSupport::TimeWithZone?

      def LastSlugModificationTime_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def LastSlugModificationTime_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def LastSlugModificationTime_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def LastSlugModificationTime_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def LastSlugModificationTime_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def LastSlugModificationTime_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_LastSlugModificationTime: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_LastSlugModificationTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_LastSlugModificationTime?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_LastSlugModificationTime!: () -> void

      def clear_LastSlugModificationTime_change: () -> void

      def LastSlugModificationTime_before_type_cast: () -> ::Time?

      def LastSlugModificationTime_for_database: () -> ::Time?

      def Slug: () -> ::String?

      def Slug=: (::String?) -> ::String?

      def Slug?: () -> bool

      def Slug_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def Slug_change: () -> [ ::String?, ::String? ]

      def Slug_will_change!: () -> void

      def Slug_was: () -> ::String?

      def Slug_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def Slug_previous_change: () -> ::Array[::String?]?

      def Slug_previously_was: () -> ::String?

      def Slug_before_last_save: () -> ::String?

      def Slug_change_to_be_saved: () -> ::Array[::String?]?

      def Slug_in_database: () -> ::String?

      def saved_change_to_Slug: () -> ::Array[::String?]?

      def saved_change_to_Slug?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_Slug?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_Slug!: () -> void

      def clear_Slug_change: () -> void

      def Slug_before_type_cast: () -> ::String?

      def Slug_for_database: () -> ::String?

      def ScienceDegreeId: () -> ::Integer?

      def ScienceDegreeId=: (::Integer?) -> ::Integer?

      def ScienceDegreeId?: () -> bool

      def ScienceDegreeId_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def ScienceDegreeId_change: () -> [ ::Integer?, ::Integer? ]

      def ScienceDegreeId_will_change!: () -> void

      def ScienceDegreeId_was: () -> ::Integer?

      def ScienceDegreeId_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def ScienceDegreeId_previous_change: () -> ::Array[::Integer?]?

      def ScienceDegreeId_previously_was: () -> ::Integer?

      def ScienceDegreeId_before_last_save: () -> ::Integer?

      def ScienceDegreeId_change_to_be_saved: () -> ::Array[::Integer?]?

      def ScienceDegreeId_in_database: () -> ::Integer?

      def saved_change_to_ScienceDegreeId: () -> ::Array[::Integer?]?

      def saved_change_to_ScienceDegreeId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_ScienceDegreeId?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_ScienceDegreeId!: () -> void

      def clear_ScienceDegreeId_change: () -> void

      def ScienceDegreeId_before_type_cast: () -> ::Integer?

      def ScienceDegreeId_for_database: () -> ::Integer?

      def ExternalId: () -> ::String?

      def ExternalId=: (::String?) -> ::String?

      def ExternalId?: () -> bool

      def ExternalId_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def ExternalId_change: () -> [ ::String?, ::String? ]

      def ExternalId_will_change!: () -> void

      def ExternalId_was: () -> ::String?

      def ExternalId_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def ExternalId_previous_change: () -> ::Array[::String?]?

      def ExternalId_previously_was: () -> ::String?

      def ExternalId_before_last_save: () -> ::String?

      def ExternalId_change_to_be_saved: () -> ::Array[::String?]?

      def ExternalId_in_database: () -> ::String?

      def saved_change_to_ExternalId: () -> ::Array[::String?]?

      def saved_change_to_ExternalId?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_ExternalId?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_ExternalId!: () -> void

      def clear_ExternalId_change: () -> void

      def ExternalId_before_type_cast: () -> ::String?

      def ExternalId_for_database: () -> ::String?

      def ExternalType: () -> ::String?

      def ExternalType=: (::String?) -> ::String?

      def ExternalType?: () -> bool

      def ExternalType_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def ExternalType_change: () -> [ ::String?, ::String? ]

      def ExternalType_will_change!: () -> void

      def ExternalType_was: () -> ::String?

      def ExternalType_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def ExternalType_previous_change: () -> ::Array[::String?]?

      def ExternalType_previously_was: () -> ::String?

      def ExternalType_before_last_save: () -> ::String?

      def ExternalType_change_to_be_saved: () -> ::Array[::String?]?

      def ExternalType_in_database: () -> ::String?

      def saved_change_to_ExternalType: () -> ::Array[::String?]?

      def saved_change_to_ExternalType?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_ExternalType?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_ExternalType!: () -> void

      def clear_ExternalType_change: () -> void

      def ExternalType_before_type_cast: () -> ::String?

      def ExternalType_for_database: () -> ::String?

      def StartOfWorkingExperienceDate: () -> ::ActiveSupport::TimeWithZone?

      def StartOfWorkingExperienceDate=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

      def StartOfWorkingExperienceDate?: () -> bool

      def StartOfWorkingExperienceDate_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def StartOfWorkingExperienceDate_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def StartOfWorkingExperienceDate_will_change!: () -> void

      def StartOfWorkingExperienceDate_was: () -> ::ActiveSupport::TimeWithZone?

      def StartOfWorkingExperienceDate_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def StartOfWorkingExperienceDate_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def StartOfWorkingExperienceDate_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def StartOfWorkingExperienceDate_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def StartOfWorkingExperienceDate_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def StartOfWorkingExperienceDate_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_StartOfWorkingExperienceDate: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_StartOfWorkingExperienceDate?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_StartOfWorkingExperienceDate?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_StartOfWorkingExperienceDate!: () -> void

      def clear_StartOfWorkingExperienceDate_change: () -> void

      def StartOfWorkingExperienceDate_before_type_cast: () -> ::Time?

      def StartOfWorkingExperienceDate_for_database: () -> ::Time?

      def AboutMyselfTranslations: () -> untyped

      def AboutMyselfTranslations=: (untyped) -> untyped

      def AboutMyselfTranslations?: () -> bool

      def AboutMyselfTranslations_changed?: (?from: untyped, ?to: untyped) -> bool

      def AboutMyselfTranslations_change: () -> [ untyped, untyped ]

      def AboutMyselfTranslations_will_change!: () -> void

      def AboutMyselfTranslations_was: () -> untyped

      def AboutMyselfTranslations_previously_changed?: (?from: untyped, ?to: untyped) -> bool

      def AboutMyselfTranslations_previous_change: () -> ::Array[untyped]?

      def AboutMyselfTranslations_previously_was: () -> untyped

      def AboutMyselfTranslations_before_last_save: () -> untyped

      def AboutMyselfTranslations_change_to_be_saved: () -> ::Array[untyped]?

      def AboutMyselfTranslations_in_database: () -> untyped

      def saved_change_to_AboutMyselfTranslations: () -> ::Array[untyped]?

      def saved_change_to_AboutMyselfTranslations?: (?from: untyped, ?to: untyped) -> bool

      def will_save_change_to_AboutMyselfTranslations?: (?from: untyped, ?to: untyped) -> bool

      def restore_AboutMyselfTranslations!: () -> void

      def clear_AboutMyselfTranslations_change: () -> void

      def AboutMyselfTranslations_before_type_cast: () -> untyped?

      def AboutMyselfTranslations_for_database: () -> untyped?

      def InternalId: () -> ::String

      def InternalId=: (::String) -> ::String

      def InternalId?: () -> bool

      def InternalId_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def InternalId_change: () -> [ ::String?, ::String? ]

      def InternalId_will_change!: () -> void

      def InternalId_was: () -> ::String?

      def InternalId_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def InternalId_previous_change: () -> ::Array[::String?]?

      def InternalId_previously_was: () -> ::String?

      def InternalId_before_last_save: () -> ::String?

      def InternalId_change_to_be_saved: () -> ::Array[::String?]?

      def InternalId_in_database: () -> ::String?

      def saved_change_to_InternalId: () -> ::Array[::String?]?

      def saved_change_to_InternalId?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_InternalId?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_InternalId!: () -> void

      def clear_InternalId_change: () -> void

      def InternalId_before_type_cast: () -> ::String

      def InternalId_for_database: () -> ::String

      def IsConsultingByCommunicationMeans: () -> bool?

      def IsConsultingByCommunicationMeans=: (bool?) -> bool?

      def IsConsultingByCommunicationMeans?: () -> bool

      def IsConsultingByCommunicationMeans_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsConsultingByCommunicationMeans_change: () -> [ bool?, bool? ]

      def IsConsultingByCommunicationMeans_will_change!: () -> void

      def IsConsultingByCommunicationMeans_was: () -> bool?

      def IsConsultingByCommunicationMeans_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsConsultingByCommunicationMeans_previous_change: () -> ::Array[bool?]?

      def IsConsultingByCommunicationMeans_previously_was: () -> bool?

      def IsConsultingByCommunicationMeans_before_last_save: () -> bool?

      def IsConsultingByCommunicationMeans_change_to_be_saved: () -> ::Array[bool?]?

      def IsConsultingByCommunicationMeans_in_database: () -> bool?

      def saved_change_to_IsConsultingByCommunicationMeans: () -> ::Array[bool?]?

      def saved_change_to_IsConsultingByCommunicationMeans?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_IsConsultingByCommunicationMeans?: (?from: bool?, ?to: bool?) -> bool

      def restore_IsConsultingByCommunicationMeans!: () -> void

      def clear_IsConsultingByCommunicationMeans_change: () -> void

      def IsConsultingByCommunicationMeans_before_type_cast: () -> bool?

      def IsConsultingByCommunicationMeans_for_database: () -> bool?

      def TitleAfterRefValue: () -> ::String?

      def TitleAfterRefValue=: (::String?) -> ::String?

      def TitleAfterRefValue?: () -> bool

      def TitleAfterRefValue_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def TitleAfterRefValue_change: () -> [ ::String?, ::String? ]

      def TitleAfterRefValue_will_change!: () -> void

      def TitleAfterRefValue_was: () -> ::String?

      def TitleAfterRefValue_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def TitleAfterRefValue_previous_change: () -> ::Array[::String?]?

      def TitleAfterRefValue_previously_was: () -> ::String?

      def TitleAfterRefValue_before_last_save: () -> ::String?

      def TitleAfterRefValue_change_to_be_saved: () -> ::Array[::String?]?

      def TitleAfterRefValue_in_database: () -> ::String?

      def saved_change_to_TitleAfterRefValue: () -> ::Array[::String?]?

      def saved_change_to_TitleAfterRefValue?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_TitleAfterRefValue?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_TitleAfterRefValue!: () -> void

      def clear_TitleAfterRefValue_change: () -> void

      def TitleAfterRefValue_before_type_cast: () -> ::String?

      def TitleAfterRefValue_for_database: () -> ::String?

      def TitleBeforeRefValue: () -> ::String?

      def TitleBeforeRefValue=: (::String?) -> ::String?

      def TitleBeforeRefValue?: () -> bool

      def TitleBeforeRefValue_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def TitleBeforeRefValue_change: () -> [ ::String?, ::String? ]

      def TitleBeforeRefValue_will_change!: () -> void

      def TitleBeforeRefValue_was: () -> ::String?

      def TitleBeforeRefValue_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def TitleBeforeRefValue_previous_change: () -> ::Array[::String?]?

      def TitleBeforeRefValue_previously_was: () -> ::String?

      def TitleBeforeRefValue_before_last_save: () -> ::String?

      def TitleBeforeRefValue_change_to_be_saved: () -> ::Array[::String?]?

      def TitleBeforeRefValue_in_database: () -> ::String?

      def saved_change_to_TitleBeforeRefValue: () -> ::Array[::String?]?

      def saved_change_to_TitleBeforeRefValue?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_TitleBeforeRefValue?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_TitleBeforeRefValue!: () -> void

      def clear_TitleBeforeRefValue_change: () -> void

      def TitleBeforeRefValue_before_type_cast: () -> ::String?

      def TitleBeforeRefValue_for_database: () -> ::String?

      def PartyVerificationStatusRefValue: () -> ::String?

      def PartyVerificationStatusRefValue=: (::String?) -> ::String?

      def PartyVerificationStatusRefValue?: () -> bool

      def PartyVerificationStatusRefValue_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def PartyVerificationStatusRefValue_change: () -> [ ::String?, ::String? ]

      def PartyVerificationStatusRefValue_will_change!: () -> void

      def PartyVerificationStatusRefValue_was: () -> ::String?

      def PartyVerificationStatusRefValue_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def PartyVerificationStatusRefValue_previous_change: () -> ::Array[::String?]?

      def PartyVerificationStatusRefValue_previously_was: () -> ::String?

      def PartyVerificationStatusRefValue_before_last_save: () -> ::String?

      def PartyVerificationStatusRefValue_change_to_be_saved: () -> ::Array[::String?]?

      def PartyVerificationStatusRefValue_in_database: () -> ::String?

      def saved_change_to_PartyVerificationStatusRefValue: () -> ::Array[::String?]?

      def saved_change_to_PartyVerificationStatusRefValue?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_PartyVerificationStatusRefValue?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_PartyVerificationStatusRefValue!: () -> void

      def clear_PartyVerificationStatusRefValue_change: () -> void

      def PartyVerificationStatusRefValue_before_type_cast: () -> ::String?

      def PartyVerificationStatusRefValue_for_database: () -> ::String?

      def PartyVerificationUpdateDate: () -> ::ActiveSupport::TimeWithZone?

      def PartyVerificationUpdateDate=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

      def PartyVerificationUpdateDate?: () -> bool

      def PartyVerificationUpdateDate_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def PartyVerificationUpdateDate_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def PartyVerificationUpdateDate_will_change!: () -> void

      def PartyVerificationUpdateDate_was: () -> ::ActiveSupport::TimeWithZone?

      def PartyVerificationUpdateDate_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def PartyVerificationUpdateDate_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def PartyVerificationUpdateDate_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def PartyVerificationUpdateDate_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def PartyVerificationUpdateDate_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def PartyVerificationUpdateDate_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_PartyVerificationUpdateDate: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_PartyVerificationUpdateDate?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_PartyVerificationUpdateDate?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_PartyVerificationUpdateDate!: () -> void

      def clear_PartyVerificationUpdateDate_change: () -> void

      def PartyVerificationUpdateDate_before_type_cast: () -> ::Time?

      def PartyVerificationUpdateDate_for_database: () -> ::Time?

      def IsHealth24: () -> bool

      def IsHealth24=: (bool) -> bool

      def IsHealth24?: () -> bool

      def IsHealth24_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsHealth24_change: () -> [ bool?, bool? ]

      def IsHealth24_will_change!: () -> void

      def IsHealth24_was: () -> bool?

      def IsHealth24_previously_changed?: (?from: bool?, ?to: bool?) -> bool

      def IsHealth24_previous_change: () -> ::Array[bool?]?

      def IsHealth24_previously_was: () -> bool?

      def IsHealth24_before_last_save: () -> bool?

      def IsHealth24_change_to_be_saved: () -> ::Array[bool?]?

      def IsHealth24_in_database: () -> bool?

      def saved_change_to_IsHealth24: () -> ::Array[bool?]?

      def saved_change_to_IsHealth24?: (?from: bool?, ?to: bool?) -> bool

      def will_save_change_to_IsHealth24?: (?from: bool?, ?to: bool?) -> bool

      def restore_IsHealth24!: () -> void

      def clear_IsHealth24_change: () -> void

      def IsHealth24_before_type_cast: () -> bool

      def IsHealth24_for_database: () -> bool

      def YearOfBirth: () -> ::Integer?

      def YearOfBirth=: (::Integer?) -> ::Integer?

      def YearOfBirth?: () -> bool

      def YearOfBirth_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def YearOfBirth_change: () -> [ ::Integer?, ::Integer? ]

      def YearOfBirth_will_change!: () -> void

      def YearOfBirth_was: () -> ::Integer?

      def YearOfBirth_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def YearOfBirth_previous_change: () -> ::Array[::Integer?]?

      def YearOfBirth_previously_was: () -> ::Integer?

      def YearOfBirth_before_last_save: () -> ::Integer?

      def YearOfBirth_change_to_be_saved: () -> ::Array[::Integer?]?

      def YearOfBirth_in_database: () -> ::Integer?

      def saved_change_to_YearOfBirth: () -> ::Array[::Integer?]?

      def saved_change_to_YearOfBirth?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_YearOfBirth?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_YearOfBirth!: () -> void

      def clear_YearOfBirth_change: () -> void

      def YearOfBirth_before_type_cast: () -> ::Integer?

      def YearOfBirth_for_database: () -> ::Integer?
    end
    include ::H24Auth::Party::GeneratedAttributeMethods
    module ::H24Auth::Party::GeneratedAliasAttributeMethods
      include ::H24Auth::Party::GeneratedAttributeMethods
    end
    include ::H24Auth::Party::GeneratedAliasAttributeMethods

    module ::H24Auth::Party::GeneratedAssociationMethods
    end
    include ::H24Auth::Party::GeneratedAssociationMethods

    module ::H24Auth::Party::GeneratedRelationMethods
    end

    class ::H24Auth::Party::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::H24Auth::Party]
      include ::H24Auth::Party::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::H24Auth::Party, ::Integer]
    end

    class ::H24Auth::Party::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::H24Auth::Party]
      include ::H24Auth::Party::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::H24Auth::Party, ::Integer]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::H24Auth::Party
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::H24Auth::Party]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::H24Auth::Party
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::H24Auth::Party]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::H24Auth::Party
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::H24Auth::Party]
      def reload: () -> ::Array[::H24Auth::Party]

      def replace: (::Array[::H24Auth::Party]) -> void
      def delete: (*::H24Auth::Party | ::Integer) -> ::Array[::H24Auth::Party]
      def destroy: (*::H24Auth::Party | ::Integer) -> ::Array[::H24Auth::Party]
      def <<: (*::H24Auth::Party | ::Array[::H24Auth::Party]) -> self
      def prepend: (*::H24Auth::Party | ::Array[::H24Auth::Party]) -> self
    end
  end
end

module ::H24Auth
end
class ::H24Auth::ApplicationRecord < ::ActiveRecord::Base
end
