class Catalog::Category < ApplicationRecord
  include Catalog::ProviderLinked
  include Catalog::Tree
  include Translatable
  include Catalog::Sluggable
  extend Translatable::ClassMethods

  def name_uk: () -> String?
  def name_uk=: (String? value) -> String?

  private

  def derive_depth: () -> void
  def shift_children_depth: () -> void
end
