class Catalog::GoodsGroup < ApplicationRecord
  include Catalog::ProviderLinked
  include Translatable
  extend Translatable::ClassMethods

  def name_uk: () -> String?
  def name_uk=: (String? value) -> String?
end
