class Provider::RequestLog
  WITHOUT_RESPONSE: Array[String]
  FILTERABLE: Array[String]

  def self.ransackable_attributes: (?untyped auth_object) -> Array[String]
  def self.ransackable_associations: (?untyped auth_object) -> Array[String]

  private

  def status_matches_outcome: () -> void
end
