class Order
  NAME_LENGTH: Integer
  PHONE_FORMAT: Regexp
  FILTERABLE: Array[String]

  def self.ransackable_attributes: (?untyped auth_object) -> Array[String]
  def self.ransackable_associations: (?untyped auth_object) -> Array[String]
  def self.ransackable_scopes: (?untyped auth_object) -> Array[Symbol]

  private

  def leaving_cart?: () -> bool
end
