class EnabledValidator < ActiveModel::EachValidator
  interface _Toggleable
    def active?: () -> bool
  end

  def validate_each: (ActiveModel::Validations record, Symbol attribute, _Toggleable? value) -> void
end
