class NotRepeatedValidator < ActiveModel::EachValidator
  interface _Repeatable
    def persisted?: () -> bool
    def id: () -> untyped
    def errors: () -> ActiveModel::Errors
  end

  def validate_each: (_Repeatable record, Symbol attribute, untyped value) -> void

  private

  def others: (_Repeatable record) -> Array[untyped]
  def same?: (untyped other, _Repeatable record) -> bool
end
