module Translatable : ActiveRecord::Base
  extend ActiveSupport::Concern

  def self.catalog_locale?: (Symbol | String | nil locale) -> bool

  module LocaleRestriction : ActiveRecord::Base
    extend ActiveSupport::Concern

    private

    def locale_is_a_catalog_locale: () -> void
  end

  module ClassMethods : Module
    def translatable: (*Symbol attributes, **untyped options) -> void
  end

  private

  def translations_are_in_catalog_locales: () -> void
end
