class Catalog::Goods::Form
  include Catalog::Dictionary
  include Catalog::ProviderLinked
  extend Catalog::ProviderLinked::ClassMethods

  def self.find_linked: (Provider provider, String | Integer external_id) -> Catalog::Goods::Form?
  include Translatable
  extend Translatable::ClassMethods
  extend Mobility
end
