class Catalog::Sync::Savers::Drugstore
  @linker: Catalog::Sync::Linker

  def initialize: (Catalog::Sync::Linker linker) -> void
  def call: (Pharmapoint::record record) -> Catalog::Drugstore

  private

  def attributes: (Pharmapoint::record record) -> Catalog::Sync::attributes
  def full_record_attributes: (Pharmapoint::record record) -> Catalog::Sync::attributes
  def brand: (Pharmapoint::record? brand) -> Catalog::Drugstore::Brand?
  def save_address: (Catalog::Drugstore drugstore, Pharmapoint::record record) -> void
end
