class Catalog::Sync::Savers::Drugstore
  @linker: Catalog::Sync::Linker

  def initialize: (Catalog::Sync::Linker linker) -> void
  def call: (Pharmapoint::Drugstore record) -> Catalog::Drugstore

  private

  def attributes: (Pharmapoint::Drugstore record) -> Catalog::Sync::attributes
  def contact_attributes: (Pharmapoint::Contacts contacts) -> Catalog::Sync::attributes
  def full_record_attributes: (Pharmapoint::Drugstore record) -> Catalog::Sync::attributes
  def brand: (Pharmapoint::Brand? brand) -> Catalog::Drugstore::Brand?
  def save_address: (Catalog::Drugstore drugstore, Pharmapoint::Location location) -> void
end
