class Pharmapoint::Readers::Categories
  def self.call: (Pharmapoint::json body) -> Array[Pharmapoint::record]

  def call: (Pharmapoint::json body) -> Array[Pharmapoint::record]

  private

  def node: (Pharmapoint::json record) -> Pharmapoint::record?
end
