class Pharmapoint::Readers::Dictionaries
  def self.call: (Pharmapoint::json body) -> Pharmapoint::dictionaries

  def call: (Pharmapoint::json body) -> Pharmapoint::dictionaries

  private

  def entries: (Pharmapoint::json value) -> Array[Pharmapoint::record]
  def entry: (Pharmapoint::json record) -> Pharmapoint::record?
end
