class Pharmapoint::Readers::Drugstores
  FIELDS: Hash[Symbol, Pharmapoint::Readers::Base::field]
  COMPLETENESS_KEYS: Array[String]

  def self.list: (Pharmapoint::json body) -> Array[Pharmapoint::record]
  def self.one: (Pharmapoint::json body) -> Pharmapoint::record

  def list: (Pharmapoint::json body) -> Array[Pharmapoint::record]
  def one: (Pharmapoint::json body) -> Pharmapoint::record

  private

  def base: () -> singleton(Pharmapoint::Readers::Base)
  def drugstore: (Pharmapoint::json record) -> Pharmapoint::record?
  def complete?: (Hash[String, Pharmapoint::json] record) -> bool
  def coordinates: (Pharmapoint::json record) -> Pharmapoint::record
  def week_hours: (Pharmapoint::json value) -> Array[String?]
  def brand: (Pharmapoint::json record) -> Pharmapoint::record?
end
